### ISSUE TITLE
Print Error if date not visible

### ISSUE THREAD

**Issue by shaggy2626** [jasonpraful/sevenrooms#1]
![13-12-2022-11-44-52](https://user-images.githubusercontent.com/120447538/207507954-ea3c7e90-e79d-4b40-ac84-47f847ff1bf3.png)

certain times a date won't be available if there are no available time slots at all and then then the process is ended without auto rerunning. Can we ignore that error and keep auto retrying just in case a date does it end getting displayed for my criteria?

**Comment by jasonpraful** [comment]
Incoming PR to fix this issue 😁
