### ISSUE TITLE
Complete Booking 

### ISSUE THREAD

**Issue by shaggy2626** [jasonpraful/sevenrooms#5]
Is there a way to actually confirm the booking and have these fields created in the config? So basically once it confirms the dates that a booking is available the process will complete the booking and then stop the script from rerunning. 
![14-12-2022-06-18-36](https://user-images.githubusercontent.com/120447538/207736092-b442026d-44f7-44d0-acb2-10b23433a489.png)
![14-12-2022-06-18-38](https://user-images.githubusercontent.com/120447538/207736100-4977161a-4f52-4671-ae8e-5408849c54f9.png)

**Comment by jasonpraful** [comment]
Unless we are scrapping/performing actions on the actual website (for instance, using Selenium/Puppeteer), automatically auto-filling the above fields won't be possible. 

To make the booking process easier, I have now updated the repository to send the direct link to make the booking along with the availability notification
