### ISSUE TITLE
Is it possible to check multi date at a same time?

### ISSUE THREAD

**Issue by Swagger5942** [jasonpraful/sevenrooms#8]
I tried to put

DATE_NEEDED = ['2023-01-02', '2023-01-03']

like the TIMES_NEEDED

but it doesn't work

Really appriciated your hard work!

**Comment by Swagger5942** [comment]
Also not getting notification from TG, while I checked my setup is all good

**Comment by jasonpraful** [comment]
@Swagger5942  This functionality did not exist previously, however, I have just merged a PR which should allow you to check against multiple dates.

Please notice the config change to enable this functionality.

`DATES_NEEDED = ['2024-01-02', '2024-01-03']`
